// examples/camera-example-app/src/lib/Camera.svelte
<script>
  import { invoke } from '@tauri-apps/api/core';
  import { emit } from '@tauri-apps/api/event';
  
  export async function takePicture() {
    console.log("Taking picture...");
    const response = await invoke('plugin:camera|take_picture');
    console.log("Picture taken from Câmera:", response);
    emit('pictureTaken', { url: response });
    return response;
  }

  export async function recordVideo() {
    console.log("Taking Video...");
    const response = await invoke('plugin:camera|record_video');
    console.log("Video taken from Câmera:", response);
    emit('videoRecorded', { url: response });
    return response;
  }

  let isCameraInitialized = false;

</script>

<div>
  <button on:click={takePicture}>Take Picture</button>
  <button on:click={recordVideo}>Record Video</button>
</div>

<style>
  div {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1rem;
  }

  button {
    padding: 0.5rem 1rem;
    font-size: 1rem;
    cursor: pointer;
  }

  button:disabled {
    background-color: #ccc;
    cursor: not-allowed;
  }
</style>

// examples/camera-app/src/app/camera/camera.component.ts
import { Component, signal } from "@angular/core";
import { invoke } from "@tauri-apps/api/core";
import { emit } from "@tauri-apps/api/event";


export interface TakePictureResponse {
  imageData: string;
    width: number;
    height: number;
}
export interface TakeVideoResponse {
  videoData: string;
    width: number;
    height: number;
}


@Component({
    selector: "app-camera",
    imports: [],
    templateUrl: "./camera.component.html",
    styleUrl: "./camera.component.scss",
})
export class CameraComponent {
    takenVideo = signal<TakeVideoResponse | null>(null);
    takenPicture = signal<TakePictureResponse | null>(null);
    emptyReturn = false;

    async recordVideo() {
        console.log("Taking Video...");
        try {
            this.takenVideo.set(null);
            const response = await invoke("plugin:camera|record_video");
            console.log("Video taken from Câmera:", response);
            emit("videoRecorded", { url: response });
            this.takenVideo.set(response as TakeVideoResponse);
        } catch (error) {
            console.error("Error recording video:", error);
            this.emptyReturn = true;
        }
    }

    async takePicture() {
        console.log("Taking picture...");
        try {
            this.takenPicture.set(null);
            const response = await invoke("plugin:camera|take_picture");
            console.log("Picture taken from Câmera:", response);
            emit("pictureTaken", { url: response });
            this.takenPicture.set(response as TakePictureResponse);
        } catch (error) {
            console.error("Error taking picture:", error);
            this.emptyReturn = true;
        }
    }
}

<div>
  <button (click)="takePicture()">Take Picture</button>
  <button (click)="recordVideo()">Record Video</button>
</div>
@if (takenPicture()) {
<div class="preview">
  <h3>Captured Image:</h3>
  <img [src]="'data:image/jpeg;base64, ' + takenPicture()?.imageData" alt="Captured Image" />
  <p>Size: {{takenPicture()?.width}} x {{takenPicture()?.height}}</p>
</div>
}
@if (takenVideo()) {
<div class="preview">
  <h3>Recorded Video:</h3>
  <video controls>
    <source type="video/mp4" [src]="'data:video/mp4;base64, ' + takenVideo()?.videoData" />
  </video>
  <p>Size: {{takenVideo()?.width}} x {{takenVideo()?.height}}</p>
</div>
}

@if (emptyReturn) {
  <p>
    No image or video captured.
  </p>
}
